name: 'readmissions'
version: '0.1.6'
config-version: 2
profile: 'default'


vars:
    patient: >
        {% if var('readmissions_patient_override',none) is not none %}{{var('readmissions_patient_override')}}
        {%- elif var('core_patient_override',none) is not none %}{{var('core_patient_override')}}
        {%- else %}{{ref('claims_preprocessing__patient')}}
        {%- endif %}
    encounter: >
        {% if var('readmissions_encounter_override',none) is not none %}{{var('readmissions_encounter_override')}}
        {%- elif var('core_encounter_override',none) is not none %}{{var('core_encounter_override')}}
        {%- else %}{{ref('claims_preprocessing__encounter')}}
        {%- endif %}
    condition: >
        {% if var('readmissions_condition_override',none) is not none %}{{var('readmissions_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {%- endif %}
    procedure: >
        {% if var('readmissions_procedure_override',none) is not none %}{{var('readmissions_procedure_override')}}
        {%- elif var('core_procedure_override',none) is not none %}{{var('core_procedure_override')}}
        {%- else %}{{ref('claims_preprocessing__procedure')}}
        {%- endif %}


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
