name: 'readmissions_syntegra_redshift_combined_data'
version: '0.1.5'
config-version: 2
profile: syntegra_redshift   # configuration required

vars:
    source_name: tuva        # configuration required
    source_database: tuva    # configuration required
    source_schema: staging_union       # configuration required

    src_patient: "{{ source(var('source_name'),'patient') }}"
    src_encounter: "{{ source(var('source_name'),'encounter') }}"
    src_diagnosis: "{{ source(var('source_name'),'condition') }}"
    src_procedure: "{{ source(var('source_name'),'procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  readmissions_syntegra_redshift_combined_data:
    +database: tuva
    +schema: readmissions

seeds:
  readmissions_syntegra_redshift_combined_data:
    +database: tuva
    +schema: terminology_readmissions
    +tags: terminology_readmissions
    +quote_columns: false
    discharge_status_code:
      +column_types: {discharge_status_code: varchar(8)}
    ms_drg:
      +column_types: {ms_drg: varchar(8)}

