name: 'readmissions_lean_input_on_hcup_in_our_snowflake'
version: '0.1.5'
config-version: 2
profile: readmissions_lean_input_on_hcup_in_our_snowflake   # configuration required

vars:
    source_name: hcup        # configuration required
    source_database: hcup    # configuration required
    source_schema: staging       # configuration required

    src_patient: "{{ source(var('source_name'),'stg_patient') }}"
    src_encounter: "{{ source(var('source_name'),'stg_encounter') }}"
    src_diagnosis: "{{ source(var('source_name'),'stg_diagnosis') }}"
    src_procedure: "{{ source(var('source_name'),'stg_procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  readmissions_lean_input_on_hcup_in_our_snowflake:
    +database: hcup
    +schema: readmissions_lean_input

seeds:
  readmissions_lean_input_on_hcup_in_our_snowflake:
    +database: hcup
    +schema: terminology
    +tags: terminology
    +quote_columns: false
    discharge_status_code:
      +column_types: {discharge_status_code: varchar(8)}
    ms_drg:
      +column_types: {ms_drg: varchar(8)}

