name: 'readmissions'
version: '0.1.3'
config-version: 2
profile: 'default'


vars:
## optional output config option 1 (configs apply to all tuva packages)
#    tuva_database: tuva                                     # optional: name of the database where tables from this package will be written
#                                                            # default: tuva
#
#    tuva_schema_prefix: test                                # optional: prefix (+_) that will be prerpended to all tuva package schema defaults
#                                                            # default schema: readmissions (no prefix by default)



## optional output config option 2 (package specific config), overrides option 1
#  readmissions_database: tuva                               # optional: name of the database where tables from this package will be written
#                                                            # default: tuva
#
#  readmissions_schema: test_readmissions                    # optional: name of the schema where tables from this package will be written
#                                                            # default: readmissions



### optional overrides for input data, only for use as a project
#    readmissions_input_database: tuva                       # optional: name of the database where tables from this package will be written
#                                                            # default: tuva
#
#    readmissions_input_schema: test_core                    # optional: name of the schema where tables from this package will be written
#                                                            # default: core



    patient: "{% if project_name == 'readmissions' %}{{ source('core','patient') }}{% else %}{{ref('claims_preprocessing__patient')}}{% endif %}"
    encounter: "{% if project_name == 'readmissions' %}{{ source('core','encounter') }}{% else %}{{ref('claims_preprocessing__encounter')}}{% endif %}"
    diagnosis: "{% if project_name == 'readmissions' %}{{ source('core','condition') }}{% else %}{{ref('claims_preprocessing__condition')}}{% endif %}"
    procedure: "{% if project_name == 'readmissions' %}{{ source('core','procedure') }}{% else %}{{ref('claims_preprocessing__procedure')}}{% endif %}"



model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
