name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



vars:
### optional overrides for input data, only for integration_test or use as a project
#  claims_preprocessing_input_database: tuva               # optional: name of the database where sources feeding this prorject are stored
#                                                          # default: tuva
#
#  claims_preprocessing_input_schema: test_claims_input    # optional: name of the schema where sources feeding this project are stored
#                                                          # default: claims_input



## optional output config option 1 (all tuva packages)
#  tuva_database: tuva                                     # optional: name of the database where tables from this package will be written
#                                                          # default: tuva
#
#  tuva_schema_prefix: test                                # optional: name of the schema where tables from this package will be written
#                                                          # default: core


## optional output config option 2 (package specific config), overrides option 1
#  claims_preprocessing_database: tuva                     # optional: name of the database where tables from this package will be written
#                                                          # default: tuva
#
#  claims_preprocessing_schema: test_core                  # optional: name of the schema where tables from this package will be written
#                                                          # default: core



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral