name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



#vars:
#### output config option 1, applies to all tuva packages
#  tuva_database: dev_user
#  tuva_schema_prefix: test

### output config option 2, applies to readmissions, overrides option 1
#  readmissions_database: tuva
#  readmissions_schema: test_readmissions


### input config option 1, applies to all SmartMarts
#  core_condition_override: "{{ref('condition')}}"
#  core_patient_override:   "{{ref('patient')}}"
#  core_encounter_override: "{{ref('encounter')}}"
#  core_procedure_override: "{{ref('procedure')}}"

## you can also point these to sources
#  core_condition_override: "{{source('core','condition')}}"
#  core_patient_override:   "{{source('core','patient')}}"
#  core_encounter_override: "{{source('core','encounter')}}"
#  core_procedure_override: "{{source('core','procedure')}}"


### input config option 2, applies to readmissions, overrides option 1
#  readmissions_condition_override: "{{ref('condition')}}"
#  readmissions_patient_override:   "{{ref('patient')}}"
#  readmissions_encounter_override: "{{ref('encounter')}}"
#  readmissions_procedure_override: "{{ref('procedure')}}"



### enabled/disabled configs
## applies to all packages
#  tuva_packages_enabled: false
#
### applies to readmissions only
#  readmissions_enabled: true
#  terminology_enabled: false

dispatch:
  - macro_namespace: dbt
    search_order: [ 'readmissions', 'dbt']


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
#    +database: dev_user